lane :example do
  approved_precheck

  # Do your check
  doMyCheck

  approved
end

def doMyCheck()
  puts("Are you ok? [ok, else failed]")
  answer = gets
  unless answer == "ok"
    user_error!("You're not ok so not approved!")  
  end
end
