lane :example do
  approved_precheck

  # Do your check
  #UI.user_error!("You're not ok so not approved!")
  UI.message("Checking...")

  approved
end

def doMyCheck()
  puts("Are you ok? [ok, else failed]")
  answer = gets
  unless answer == "ok"
    
  end
end
